--------------------------------------------------------------------------------
-- Promote to Staging
--------------------------------------------------------------------------------

-- Signature members
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(HIST_B) TOMBR(HIST_B);
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(STRYRPD_B) TOMBR(STRYRPD_B);

-- Prototype headers
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(HIST_H) TOMBR(HIST_H);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(STRYRPD_H) TOMBR(STRYRPD_H);

-- AR_HIST
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_HIST);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_HIST) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_HIST) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_HIST) TOMBR(AR_HIST);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_HIST) SRCFILE(WEB_5DEV/QRPGLESRC) OBJTYPE(*MODULE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AR_HIST) MODULE(WEB_5OBJ/AR_HIST) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(HIST_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_HIST));

-- AR_STRYRPD
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_STRYRPD);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_STRYRPD) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_STRYRPD) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_STRYRPD) TOMBR(AR_STRYRPD);
CL: CRTRPGMOD MODULE(WEB_5OBJ/AR_STRYRPD) SRCFILE(WEB_5DEV/QRPGLESRC) OPTION(*EVENTF) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AR_STRYRPD) MODULE(WEB_5OBJ/AR_STRYRPD) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(STRYRPD_B);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_STRYRPD));

-- AR_3035
CL: DLTOBJ OBJ(WEB_5OBJ/AR_3035) OBJTYPE(*PGM);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_3035) TOMBR(AR_3035);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_3035) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0);

-- AR_FPRPROR
--CL: DLTOBJ OBJ(WEB_5TST/AR_FPRPROR) OBJTYPE(*PGM);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_FPRPROR) TOMBR(AR_FPRPROR);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_FPRPROR) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0);

-- AC_FPRPROR
CL: DLTOBJ OBJ(WEB_5OBJ/AC_FPRPROR) OBJTYPE(*PGM);
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_FPRPROR) TOMBR(AC_FPRPROR);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_FPRPROR) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF);

-- AR_FSMPROR
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_FSMPROR) TOMBR(AR_FSMPROR);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_FSMPROR) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0);

-- AC_FSMPROR
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_FSMPROR) TOMBR(AC_FSMPROR);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_FSMPROR) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF);

-- AC_FSPROR
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_FSPPROR) TOMBR(AC_FSPPROR);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_FSPPROR) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF);

-- AR_FSPROR
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_FSPPROR) TOMBR(AR_FSPPROR);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_FSPPROR) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0);


-- delete source members from WEB_5TDV
