--------------------------------------------------------------------------------
-- In Development
--------------------------------------------------------------------------------

-- AR_HIST
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_HIST);
CL: DLTOBJ OBJ(ACS_5DEV/AR_HIST) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5DEV/AR_HIST) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5DEV/AR_HIST) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(ACS_5DEV/AR_HIST) MODULE(ACS_5DEV/AR_HIST) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(HIST_B) BNDDIR(K3SDIR);
-- CL: UPDSRVPGM SRVPGM(ACS_5DEV/AR_PRODHIS) MODULE(ACS_5DEV/AR_PRODHIS) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(PRODHIS_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(ACS_5OBJ/K3SDIR) OBJ((AR_HIST));

-- AR_3035
CL: CRTSQLRPGI OBJ(ACS_5DEV/AR_3035) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);

-- AR_STRYRPD
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_STRYRPD);
CL: DLTOBJ OBJ(ACS_5DEV/AR_STRYRPD) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5DEV/AR_STRYRPD) OBJTYPE(*MODULE);
CL: CRTRPGMOD MODULE(ACS_5DEV/AR_STRYRPD) SRCFILE(ACS_5DEV/QRPGLESRC) OPTION(*EVENTF *SRCSTMT) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(ACS_5DEV/AR_STRYRPD) MODULE(ACS_5DEV/AR_STRYRPD) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(STRYRPD_B);
--CL: UPDSRVPGM SRVPGM(ACS_5DEV/AR_STRYRPD) MODULE(ACS_5DEV/AR_STRYRPD) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(HIST_B) BNDDIR(K3SDIR)
CL: ADDBNDDIRE BNDDIR(ACS_5OBJ/K3SDIR) OBJ((AR_STRYRPD));

-- AR_FPRPROR
CL: CRTSQLRPGI OBJ(ACS_5DEV/AR_FPRPROR) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);

-- AC_FPRPROR
CL: CRTBNDCL PGM(ACS_5DEV/AC_FPRPROR) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);

-- TS_FPRPROR
CL: CRTBNDCL PGM(ACS_5DEV/TS_FPRPROR) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);

-- AR_FSMPROR
CL: CRTSQLRPGI OBJ(ACS_5DEV/AR_FSMPROR) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);

-- AC_FSMPROR
CL: CRTBNDCL PGM(ACS_5DEV/AC_FSMPROR) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);

-- TS_FSMPROR
CL: CRTBNDCL PGM(ACS_5DEV/TS_FSMPROR) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);

-- AR_FSPPROR
CL: CRTSQLRPGI OBJ(ACS_5DEV/AR_FSPPROR) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);

-- AC_FSPPROR
CL: CRTBNDCL PGM(ACS_5DEV/AC_FSPPROR) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);

-- TS_FSPPROR
CL: CRTBNDCL PGM(ACS_5DEV/TS_FSPPROR) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);



