-- GH822

--------------------------------------------------------------------------------
-- Set Up
--------------------------------------------------------------------------------
CL: ADDPFM FILE(QGPL/QCLSRC) MBR(APIFTPOUT) TEXT('API FTP Upload Output') SRCTYPE(TXT);
CL: ADDPFM FILE(QGPL/QCLSRC) MBR(APIFTPIN) TEXT('API FTP Upload Input') SRCTYPE(TXT);



--------------------------------------------------------------------------------
-- In Development
--------------------------------------------------------------------------------

-- Command
CL: CRTCMD CMD(ACS_5OBJ/FTPUPDAPI) PGM(ACS_5OBJ/FTPUPDAPI) SRCFILE(ACS_5DEV/QCMDSRC) ALLOW(*ALL) CURLIB(*NOCHG) PRDLIB(*NOCHG);

-- CL Program(s)
CL: CRTBNDCL PGM(ACS_5OBJ/FTPUPDAPI) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: CRTBNDCL PGM(ACS_5OBJ/FTPUPDAPI2) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);

-- FTPUPDAPI
--CL: CRTSQLRPGI OBJ(ACS_5OBJ/FTPUPDAPIR) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTBNDRPG PGM(ACS_5OBJ/FTPUPDAPIR) SRCFILE(ACS_5DEV/QRPGLESRC) DBGVIEW(*SOURCE);

CL: GRTOBJAUT OBJ(ACS_5OBJ/*ALL) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Integrated Testing Environment
--------------------------------------------------------------------------------

-- Command
CL: CPYSRCF FROMFILE(ACS_5DEV/QCMDSRC) TOFILE(WEB_5TDV/QCMDSRC) FROMMBR(FTPUPDAPI) TOMBR(FTPUPDAPI);
CL: CRTCMD CMD(WEB_5TST/FTPUPDAPI) PGM(WEB_5DEV/FTPUPDAPI) SRCFILE(WEB_5TDV/QCMDSRC) ALLOW(*ALL) CURLIB(*NOCHG) PRDLIB(*NOCHG);

-- CL Program(s)
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(FTPUPDAPI) TOMBR(FTPUPDAPI);
CL: CRTBNDCL PGM(WEB_5TST/FTPUPDAPI) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(FTPUPDAPI2) TOMBR(FTPUPDAPI2);
CL: CRTBNDCL PGM(WEB_5TST/FTPUPDAPI2) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);

-- RPG Program(s)
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(FTPUPDAPIR) TOMBR(FTPUPDAPIR);
CL: CRTBNDRPG PGM(WEB_5TST/FTPUPDAPIR) SRCFILE(WEB_5TDV/QRPGLESRC) DBGVIEW(*SOURCE);

CL: GRTOBJAUT OBJ(WEB_5TST/FTPUPDAPI) OBJTYPE(*CMD) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/FTPUPDAPI) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/FTPUPDAPI2) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/FTPUPDAPIR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Deployment
--------------------------------------------------------------------------------

-- Command(s)
CL: CPYSRCF FROMFILE(WEB_5TDV/QCMDSRC) TOFILE(WEB_5DEV/QCMDSRC) FROMMBR(FTPUPDAPI) TOMBR(FTPUPDAPI);
CL: CRTCMD CMD(WEB_5OBJ/FTPUPDAPI) PGM(WEB_5OBJ/FTPUPDAPI) SRCFILE(WEB_5DEV/QCMDSRC) ALLOW(*ALL) CURLIB(*NOCHG) PRDLIB(*NOCHG);

-- CL Program(s)
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(FTPUPDAPI) TOMBR(FTPUPDAPI);
CL: CRTBNDCL PGM(WEB_5OBJ/FTPUPDAPI) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF);
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(FTPUPDAPI2) TOMBR(FTPUPDAPI2);
CL: CRTBNDCL PGM(WEB_5OBJ/FTPUPDAPI2) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF);

-- RPG Program(s)
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(FTPUPDAPIR) TOMBR(FTPUPDAPIR);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/FTPUPDAPIR) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0);

CL: GRTOBJAUT OBJ(WEB_5OBJ/FTPUPDAPI) OBJTYPE(*CMD) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/FTPUPDAPI) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/FTPUPDAPI2) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/FTPUPDAPIR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);



--------------------------------------------------------------------------------
-- Hotfix to FTP site
--------------------------------------------------------------------------------

-- Clear save file
CL: CLRSAVF FILE(QGPL/r6objects);

-- Add objects to save file
CL: SAVOBJ OBJ(AR_ADDLINK AC_ADDLINK) LIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/r6objects);

-- Upload savefile to Smartfile FTP site
--  (on Conan Dev)
FTP RMTSYS(K3S.SMARTFILE.COM)
> cd /R6_Deployment/Customer_Access
  250 "/R6_Deployment/Customer_Access" is the current directory.
> bin
  200 Type set to: Binary.
> put r6objects                                                        
229 Entering extended passive mode (|||21344|).                            
125 Data connection already open. Transfer starting.                       
226 Transfer complete.                                                     
2356992 bytes transferred in 0.721 seconds. Transfer rate 3270.406 KB/sec. 
