-- GH833

-- 1. Name this file after its corresponding GitHub issue
-- 2. Search for <api_name> and replace with API program name (shift + command + H)
-- 3. Remove service program compile commands if not used
-- 4. Search for <api_text> and replace with API text
-- 5. Search for <api_test_text> and replace with API test text
-- 6. If service programs are involved...
--    A. Search for <srvpgm_name> and replace with service program name
--    B. Search for <srvpgm_text> and replace with service program text
--

--------------------------------------------------------------------------------
-- Set Up
--------------------------------------------------------------------------------

-- CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(PRODFOR_H) TOMBR(PRODFOR_H);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_C3041) TOMBR(AR_C3041);


-- CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT12) TOMBR(AR_CPYHT12);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT13) TOMBR(AR_CPYHT13);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT52) TOMBR(AR_CPYHT52);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPYHT12) TOMBR(AC_CPYHT12);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPYHT13) TOMBR(AC_CPYHT13);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPYHT52) TOMBR(AC_CPYHT52);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPYHT12) TOMBR(TS_CPYHT12);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPYHT13) TOMBR(TS_CPYHT13);
-- CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPYHT52) TOMBR(TS_CPYHT52);



--------------------------------------------------------------------------------
-- In Development
--------------------------------------------------------------------------------

-- API Program(s)
-- AR_CPYHT12
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPYHT12) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 12');

-- AC_CPYHT12
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPYHT12) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 12');

-- TS_CPYHT12
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPYHT12) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPYHT12');

-- AR_CPYHT13
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPYHT13) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 13');

-- AC_CPYHT13
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPYHT13) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 13');

-- TS_CPYHT13
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPYHT13) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPYHT13');

-- AR_CPYHT52
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPYHT52) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 52');

-- AC_CPYHT52
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPYHT52) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 52');

-- TS_CPYHT52
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPYHT52) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPYHT52');

-- Authority
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

--------------------------------------------------------------------------------
-- Integrated Testing Environment
--------------------------------------------------------------------------------

-- API Program(s)
-- AR_CPYHT12
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPYHT12) TOMBR(AR_CPYHT12);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPYHT12) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 12');

-- AC_CPYHT12
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPYHT12) TOMBR(AC_CPYHT12);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPYHT12) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 12');

-- TS_CPYHT12
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPYHT12) TOMBR(TS_CPYHT12);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPYHT12) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPYHT12');

-- AR_CPYHT13
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPYHT13) TOMBR(AR_CPYHT13);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPYHT13) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 13');

-- AC_CPYHT13
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPYHT13) TOMBR(AC_CPYHT13);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPYHT13) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 13');

-- TS_CPYHT13
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPYHT13) TOMBR(TS_CPYHT13);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPYHT13) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPYHT13');

-- AR_CPYHT52
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPYHT52) TOMBR(AR_CPYHT52);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPYHT52) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 52');

-- AC_CPYHT52
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPYHT52) TOMBR(AC_CPYHT52);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPYHT52) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 52');

-- TS_CPYHT52
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPYHT52) TOMBR(TS_CPYHT52);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPYHT52) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPYHT52');

-- Authority
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

--------------------------------------------------------------------------------
-- Deployment
--------------------------------------------------------------------------------

-- API Program(s)
-- AR_CPYHT12
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT12) TOMBR(AR_CPYHT12);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPYHT12) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 12');

-- AC_CPYHT12
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPYHT12) TOMBR(AC_CPYHT12);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPYHT12) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History off Product 12');

-- TS_CPYHT12
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPYHT12) TOMBR(TS_CPYHT12);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPYHT12) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_CPYHT12');

-- AR_CPYHT13
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT13) TOMBR(AR_CPYHT13);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPYHT13) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 13');

-- AC_CPYHT13
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPYHT13) TOMBR(AC_CPYHT13);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPYHT13) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History off Product 13');

-- TS_CPYHT13
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPYHT13) TOMBR(TS_CPYHT13);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPYHT13) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_CPYHT13');

-- AR_CPYHT52
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT52) TOMBR(AR_CPYHT52);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPYHT52) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 52');

-- AC_CPYHT52
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPYHT52) TOMBR(AC_CPYHT52);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPYHT52) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History off Product 52');

-- TS_CPYHT52
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPYHT52) TOMBR(TS_CPYHT52);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPYHT12) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_CPYHT52');

-- Authority
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Hotfix to self-hosted
--------------------------------------------------------------------------------

-- Clear save file
CL: CLRSAVF FILE(QGPL/r6objects);

-- Add objects to save file
CL: SAVOBJ OBJ(AC_CPYHT12 AR_CPYHT12 TS_CPYHT12) LIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/r6objects);

-- Upload savefile to Smartfile FTP site
--  (on Conan Dev)
FTP RMTSYS(K3S.SMARTFILE.COM)
> cd /R6_Deployment/Customer_Access
  250 "/R6_Deployment/Customer_Access" is the current directory.
> bin
  200 Type set to: Binary.
> put r6objects                                                        
229 Entering extended passive mode (|||21344|).                            
125 Data connection already open. Transfer starting.                       
226 Transfer complete.                                                     
2356992 bytes transferred in 0.721 seconds. Transfer rate 3270.406 KB/sec. 


--------------------------------------------------------------------------------
-- Hotfix to hosted
--------------------------------------------------------------------------------
-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API object in error to save file
CL: SAVOBJ OBJ(AR_CPYHT12 AR_LTMAPOR) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEAN_PUTL;

-- on Leno...

-- Restore the save file objects to library DMO
CL: RSTOBJ OBJ(*ALL) SAVLIB(ACS_5DEV) DEV(*SAVF) SAVF(QGPL/APIMISSCHK) RSTLIB(DMO_5OBJ) ALWOBJDIF(*ALL) MBROPT(*ALL);


--------------------------------------------------------------------------------
-- Hotfix to self-hosted
--------------------------------------------------------------------------------
-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API object in error to save file
CL: SAVOBJ OBJ(AR_PUSORDR AR_LTMAPOR) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEAN_PUTL;


--------------------------------------------------------------------------------
-- Hotfix to Conan DR
--------------------------------------------------------------------------------

-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API objects to save file
CL: SAVOBJ OBJ(AR_PUSORDR AR_LTMAPOR) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEANPUTDR;
