-- GH832

-- 1. Name this file after its corresponding GitHub issue
-- 2. Search for <api_name> and replace with API program name (shift + command + H)
-- 3. Remove service program compile commands if not used
-- 4. Search for <api_text> and replace with API text
-- 5. Search for <api_test_text> and replace with API test text
-- 6. If service programs are involved...
--    A. Search for <srvpgm_name> and replace with service program name
--    B. Search for <srvpgm_text> and replace with service program text



-- AR_STSPROD In ITE
-- AR_CPAHT52 In ITE
-- AR_CPAHT13 In ITE
-- AR_CPAHT52 In ITE
-- AR_CPYHT12 In ITE
-- AR_CPYHT13 In ITE
-- AR_CPYHT52 In ITE
-- AR_HHHPROD In ITE
-- AR_UAVPROR In ITE








--------------------------------------------------------------------------------
-- Set Up
--------------------------------------------------------------------------------

-- Copy Books
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_3707_H) TOMBR(AR_3707_H);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_PQSA_H) TOMBR(AR_PQSA_H);

-- CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR() TOMBR();
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPAHT12) TOMBR(AR_CPAHT12);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPAHT13) TOMBR(AR_CPAHT13);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPAHT52) TOMBR(AR_CPAHT52);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT12) TOMBR(AR_CPYHT12);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT13) TOMBR(AR_CPYHT13);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT52) TOMBR(AR_CPYHT52);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_STSPROD) TOMBR(AR_STSPROD);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_HHHPROD) TOMBR(AR_HHHPROD);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_UAVPROR) TOMBR(AR_UAVPROR);

CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPAHT12) TOMBR(AC_CPAHT12);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPAHT13) TOMBR(AC_CPAHT13);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPAHT52) TOMBR(AC_CPAHT52);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPYHT12) TOMBR(AC_CPYHT12);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPYHT13) TOMBR(AC_CPYHT13);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPYHT52) TOMBR(AC_CPYHT52);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_STSPROD) TOMBR(AC_STSPROD);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_HHHPROD) TOMBR(AC_HHHPROD);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_UAVPROR) TOMBR(AC_UAVPROR);

CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPAHT12) TOMBR(TS_CPAHT12);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPAHT13) TOMBR(TS_CPAHT13);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPAHT52) TOMBR(TS_CPAHT52);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPYHT12) TOMBR(TS_CPYHT12);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPYHT13) TOMBR(TS_CPYHT13);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_CPYHT52) TOMBR(TS_CPYHT52);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_STSPROD) TOMBR(TS_STSPROD);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_HHHPROD) TOMBR(TS_HHHPROD);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_UAVPROR) TOMBR(TS_UAVPROR);

--------------------------------------------------------------------------------
-- In Development
--------------------------------------------------------------------------------

-- Service Program(s)


-- API Program(s)
-- STSPROD
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_STSPROD) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web-update a product(UsrSts-Freeze & Probate Date)');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_STSPROD) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web-Product Update (Status, Freeze & Probation Dt)');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_STSPROD) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_STSPROD');

-- CPAHT12
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPAHT12) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all locations 12');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPAHT12) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History to product at allLocs. AR_CPAHT12');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPAHT12) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPAHT12');

-- CPAHT13
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPAHT13) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all locations 13');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPAHT13) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History 2 product at Locs. 13');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPAHT13) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPAHT13');

-- CPAHT52
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPAHT52) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all Locations 52');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPAHT52) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History to product at all Locs. 52');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPAHT52) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPAHT52');

-- CPYHT12
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPYHT12) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 12');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPYHT12) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 12       AR_CPYHT12');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPYHT12) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPYHT12');

-- CPYHT13
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPYHT13) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 13');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPYHT13) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 13       AR_CPYHT13');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPYHT13) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPYHT13');

-- CPYHT52
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPYHT52) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 52');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPYHT52) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 52       AR_CPYHT52');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPYHT52) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPYHT52');

-- HHHPROD
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_HHHPROD) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Set New Products to Slow/Probation');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_HHHPROD) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Chg Usr & Sys stats if sys = N    AR_HHHPROD');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_HHHPROD) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_HHHPROD');

-- UAVPROR
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_UAVPROR) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Update average of Product');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_UAVPROR) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Invoke AR_UVPROR');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_UAVPROR) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_UAVPROR');



-- Authority
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Integrated Testing Environment
--------------------------------------------------------------------------------

-- API Program(s)
-- STSPROD
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_STSPROD) TOMBR(AR_STSPROD);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_STSPROD) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('WEB-update a product(UsrSts-Freeze & Probate Date)');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_STSPROD) TOMBR(AC_STSPROD);
CL: CRTBNDCL PGM(WEB_5TST/AC_STSPROD) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web-Product Update (Status, Freeze & Probation Dt)');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_STSPROD) TOMBR(TS_STSPROD);
CL: CRTBNDCL PGM(WEB_5TST/TS_STSPROD) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_STSPROD');

-- CPAHT12
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPAHT12) TOMBR(AR_CPAHT12);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPAHT12) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all Locations 12');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPAHT12) TOMBR(AC_CPAHT12);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPAHT12) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History 2 product at Locs. AR_CPAHT12');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPAHT12) TOMBR(TS_CPAHT12);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPAHT12) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPAHT12');

-- CPAHT13
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPAHT13) TOMBR(AR_CPAHT13);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPAHT13) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all Locations 13');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPAHT13) TOMBR(AC_CPAHT13);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPAHT13) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History 2 product at Locs. 13');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPAHT13) TOMBR(TS_CPAHT13);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPAHT13) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPAHT13');

-- CPAHT52
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPAHT52) TOMBR(AR_CPAHT52);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPAHT52) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all Locations 52');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPAHT52) TOMBR(AC_CPAHT52);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPAHT52) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History 2 product at Locs. 52');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPAHT52) TOMBR(TS_CPAHT52);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPAHT52) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPAHT52');

-- CPYHT12
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPYHT12) TOMBR(AR_CPYHT12);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPYHT12) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 12');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPYHT12) TOMBR(AC_CPYHT12);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPYHT12) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 12       AR_CPYHT12');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPYHT12) TOMBR(TS_CPYHT12);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPYHT12) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPYHT12');

-- CPYHT13
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPYHT13) TOMBR(AR_CPYHT13);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPYHT13) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 13');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPYHT13) TOMBR(AC_CPYHT13);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPYHT13) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 13       AR_CPYHT13');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPYHT13) TOMBR(TS_CPYHT13);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPYHT13) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPYHT13');

-- CPYHT52
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPYHT52) TOMBR(AR_CPYHT52);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPYHT52) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 52');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPYHT52) TOMBR(AC_CPYHT52);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPYHT52) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Copy History off Product 52       AR_CPYHT52');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPYHT52) TOMBR(TS_CPYHT52);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPYHT52) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_CPYHT52');

-- HHHPROD
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_HHHPROD) TOMBR(AR_HHHPROD);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_HHHPROD) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Set New Products to Slow/Probation');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_HHHPROD) TOMBR(AC_HHHPROD);
CL: CRTBNDCL PGM(WEB_5TST/AC_HHHPROD) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Chg Usr & Sys stats if sys = N    AR_HHHPROD');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_HHHPROD) TOMBR(TS_HHHPROD);
CL: CRTBNDCL PGM(WEB_5TST/TS_HHHPROD) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_HHHPROD');

-- UAVPROR
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_UAVPROR) TOMBR(AR_UAVPROR);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_UAVPROR) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Update average of Product');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_UAVPROR) TOMBR(AC_UAVPROR);
CL: CRTBNDCL PGM(WEB_5TST/AC_UAVPROR) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Invoke AR_UVPROR');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_UAVPROR) TOMBR(TS_UAVPROR);
CL: CRTBNDCL PGM(WEB_5TST/TS_UAVPROR) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Testing AC_UAVPROR');


-- Authority
CL: GRTOBJAUT OBJ(WEB_5TST/AR_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Deployment
--------------------------------------------------------------------------------

-- STSPROD
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_STSPROD) TOMBR(AR_STSPROD);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_STSPROD) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('WEB-update a product(UsrSts-Freeze & Probate Date)');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_STSPROD) TOMBR(AC_STSPROD);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_STSPROD) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web-Product Update (Status, Freeze & Probation Dt)');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_STSPROD) TOMBR(TS_STSPROD);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_STSPROD) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_STSPROD');

-- CPAHT12
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPAHT12) TOMBR(AR_CPAHT12);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPAHT12) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all Locations 12');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPAHT12) TOMBR(AC_CPAHT12);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPAHT12) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History 2 product at Locs. AR_CPAHT12');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPAHT12) TOMBR(TS_CPAHT12);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPAHT12) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_CPAHT12');

-- CPAHT13
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPAHT13) TOMBR(AR_CPAHT13);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPAHT13) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all Locations 13');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPAHT13) TOMBR(AC_CPAHT13);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPAHT13) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History 2 product at Locs. 13');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPAHT13) TOMBR(TS_CPAHT13);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPAHT13) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_CPAHT13');

-- CPAHT52
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPAHT52) TOMBR(AR_CPAHT52);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPAHT52) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History to product at all Locations 52');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPAHT52) TOMBR(AC_CPAHT52);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPAHT52) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History 2 product at Locs. 52');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPAHT52) TOMBR(TS_CPAHT52);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPAHT52) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_CPAHT52');

-- CPYHT12
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT12) TOMBR(AR_CPYHT12);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPYHT12) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 12');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPYHT12) TOMBR(AC_CPYHT12);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPYHT12) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History off Product 12       AR_CPYHT12');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPYHT12) TOMBR(TS_CPYHT12);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPYHT12) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_CPYHT12');

-- CPYHT13
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT13) TOMBR(AR_CPYHT13);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPYHT13) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 13');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPYHT13) TOMBR(AC_CPYHT13);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPYHT13) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History off Product 13       AR_CPYHT13');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPYHT13) TOMBR(TS_CPYHT13);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPYHT13) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_CPYHT13');

-- CPYHT52
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPYHT52) TOMBR(AR_CPYHT52);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPYHT52) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Copy History off Product 52');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPYHT52) TOMBR(AC_CPYHT52);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPYHT52) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Copy History off Product 52       AR_CPYHT52');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPYHT52) TOMBR(TS_CPYHT52);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPYHT52) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_CPYHT52');

-- HHHPROD
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_HHHPROD) TOMBR(AR_HHHPROD);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_HHHPROD) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Set New Products to Slow/Probation');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_HHHPROD) TOMBR(AC_HHHPROD);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_HHHPROD) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Chg Usr & Sys stats if sys = N    AR_HHHPROD');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_HHHPROD) TOMBR(TS_HHHPROD);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_HHHPROD) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_HHHPROD');

-- UAVPROR
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_UAVPROR) TOMBR(AR_UAVPROR);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_UAVPROR) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Update average of Product');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_UAVPROR) TOMBR(AC_UAVPROR);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_UAVPROR) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Invoke AR_UVPROR');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_UAVPROR) TOMBR(TS_UAVPROR);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_UAVPROR) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Testing AC_UAVPROR');


CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_STSPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPAHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPAHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPYHT12) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPYHT13) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPYHT52) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_HHHPROD) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_UAVPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

--------------------------------------------------------------------------------
-- Hotfix to self-hosted
--------------------------------------------------------------------------------

-- Clear save file
CL: CLRSAVF FILE(QGPL/r6objects);

-- Add objects to save file
CL: SAVOBJ OBJ(AR_<srvpgm_name> AC_<api_name> AR_<api_name> TS_<api_name>) LIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/r6objects);

-- Upload savefile to Smartfile FTP site
--  (on Conan Dev)
FTP RMTSYS(K3S.SMARTFILE.COM)
> cd /R6_Deployment/Customer_Access
  250 "/R6_Deployment/Customer_Access" is the current directory.
> bin
  200 Type set to: Binary.
> put r6objects                                                        
229 Entering extended passive mode (|||21344|).                            
125 Data connection already open. Transfer starting.                       
226 Transfer complete.                                                     
2356992 bytes transferred in 0.721 seconds. Transfer rate 3270.406 KB/sec. 


--------------------------------------------------------------------------------
-- Hotfix to hosted
--------------------------------------------------------------------------------
-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API object in error to save file
CL: SAVOBJ OBJ(AR_<api_name> AR_LTMAPOR) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEAN_PUTL;

-- on Leno...

-- Restore the save file objects to library DMO
CL: RSTOBJ OBJ(*ALL) SAVLIB(ACS_5DEV) DEV(*SAVF) SAVF(QGPL/APIMISSCHK) RSTLIB(DMO_5OBJ) ALWOBJDIF(*ALL) MBROPT(*ALL);


--------------------------------------------------------------------------------
-- Hotfix to self-hosted
--------------------------------------------------------------------------------
-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API object in error to save file
CL: SAVOBJ OBJ(AR_PUSORDR AR_LTMAPOR) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEAN_PUTL;


--------------------------------------------------------------------------------
-- Hotfix to Conan DR
--------------------------------------------------------------------------------

-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API objects to save file
CL: SAVOBJ OBJ(AR_PUSORDR AR_LTMAPOR) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEANPUTDR;
