-- GH844

CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_OVSTK_H) TOMBR(AR_OVSTK_H);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_FWBUY_H) TOMBR(AR_FWBUY_H);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(INVRLOG_H) TOMBR(INVRLOG_H);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_INVLOG) TOMBR(AR_INVLOG);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_INVLOG) TOMBR(AC_INVLOG);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(TS_INVLOG) TOMBR(TS_INVLOG);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_INTPROD) TOMBR(AR_INTPROD);

CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_USERAPI) TOMBR(AR_USERAPI);

CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_NITTOT) TOMBR(AR_NITTOT);

CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(NITETOT_H) TOMBR(NITETOT_H);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(BUYRALG_H) TOMBR(BUYRALG_H);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_SSIREPT) TOMBR(AR_SSIREPT);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_PRIREPT) TOMBR(AC_PRIREPT);


--------------------------------------------------------------------------------
-- In Development
--------------------------------------------------------------------------------

-------------------------------------------------------
-- Run During Development
-------------------------------------------------------

-- https://www.ibm.com/docs/en/i/7.2?topic=cssiira-example-dynamic-sql-in-ile-rpg-application-that-uses-sql

-- AC_PSIMIS  (ready)
CL: CRTPRTF FILE(ACS_5OBJ/AC_PSIMIS) SRCFILE(ACS_5DEV/QDDSSRC) SRCMBR(AC_PSIMIS) IGCDTA(*N) IGCEXNCHR(*N) PAGESIZE(*N 198) IGCCHRRTT(*N) IGCCPI(*N) IGCSOSI(*N) IGCCDEFNT(*SYSVAL) REPLACE(*YES);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_PSIMIS) OBJTYPE(*ALL) USER(*PUBLIC) AUT(*ALL);

-- AR_INVRLOG  (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_INVRLOG);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_INVRLOG) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_INVRLOG) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_INVRLOG) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AR_INVRLOG) MODULE(ACS_5OBJ/AR_INVRLOG) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(INVRLOG_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_INVRLOG));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_INVRLOG) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AS_SSTOCK  (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AS_SSTOCK);
CL: DLTOBJ OBJ(ACS_5OBJ/AS_SSTOCK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AS_SSTOCK) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AS_SSTOCK) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AS_SSTOCK) MODULE(ACS_5OBJ/AS_SSTOCK) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(SSTOCK_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AS_SSTOCK));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AS_SSTOCK) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AS_PRDINVT  (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AS_PRDINVT);
CL: DLTOBJ OBJ(ACS_5OBJ/AS_PRDINVT) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AS_PRDINVT) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AS_PRDINVT) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AS_PRDINVT) MODULE(ACS_5OBJ/AS_PRDINVT) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(PRDINVT_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AS_PRDINVT));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AS_PRDINVT) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PRDINVT  (ready)
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_PRDINVT) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_PRDINVT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_PRDINVT (ready)
CL: CRTBNDCL PGM(ACS_5OBJ/AC_PRDINVT) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_PRDINVT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_INVLOG (ready)
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_INVLOG) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_INVLOG (ready)
CL: CRTBNDCL PGM(ACS_5OBJ/AC_INVLOG) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: CRTBNDCL PGM(ACS_5OBJ/TS_INVLOG) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PSIREPT (ready)
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_PSIREPT) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_PSIREPT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Integrated Testing Environment
--------------------------------------------------------------------------------

-- K3S_APIPRO
CL: CPYSRCF FROMFILE(ACS_5WEB/QRPGLESRC) TOFILE(WEB_5WEB/QRPGLESRC) FROMMBR(K3S_APIPRO) TOMBR(K3S_APIPRO);

-- AC_PSIMIS  (ready)
CL: CPYSRCF FROMFILE(ACS_5DEV/QDDSSRC) TOFILE(WEB_5TDV/QDDSSRC) FROMMBR(AC_PSIMIS) TOMBR(AC_PSIMIS);
CL: CRTPRTF FILE(WEB_5TST/AC_PSIMIS) SRCFILE(WEB_5TDV/QDDSSRC) SRCMBR(AC_PSIMIS) IGCDTA(*N) IGCEXNCHR(*N) PAGESIZE(*N 198) IGCCHRRTT(*N) IGCCPI(*N) IGCSOSI(*N) IGCCDEFNT(*SYSVAL) REPLACE(*YES);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_PSIMIS) OBJTYPE(*ALL) USER(*PUBLIC) AUT(*ALL);


-- AR_INVRLOG  (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_INVRLOG);
CL: DLTOBJ OBJ(WEB_5TST/AR_INVRLOG) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5TST/AR_INVRLOG) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_INVRLOG) TOMBR(AR_INVRLOG);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(INVRLOG_H) TOMBR(INVRLOG_H);
CL: CPYSRCF FROMFILE(ACS_5DEV/QSRVSRC) TOFILE(WEB_5TDV/QSRVSRC) FROMMBR(INVRLOG_B) TOMBR(INVRLOG_B);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_INVRLOG) SRCFILE(WEB_5TDV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CRTSRVPGM SRVPGM(WEB_5TST/AR_INVRLOG) MODULE(WEB_5TST/AR_INVRLOG) SRCFILE(WEB_5TDV/QSRVSRC) SRCMBR(INVRLOG_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_INVRLOG));
CL: GRTOBJAUT OBJ(WEB_5TST/AR_INVRLOG) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AS_SSTOCK (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AS_SSTOCK);
CL: DLTOBJ OBJ(WEB_5TST/AS_SSTOCK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5TST/AS_SSTOCK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AS_SSTOCK) TOMBR(AS_SSTOCK);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(SSTOCK_H) TOMBR(SSTOCK_H);
CL: CPYSRCF FROMFILE(ACS_5DEV/QSRVSRC) TOFILE(WEB_5TDV/QSRVSRC) FROMMBR(SSTOCK_B) TOMBR(SSTOCK_B);
CL: CRTSQLRPGI OBJ(WEB_5TST/AS_SSTOCK) SRCFILE(WEB_5TDV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CPYSRCF FROMFILE(ACS_5DEV/QSRVSRC) TOFILE(WEB_5TDV/QSRVSRC) FROMMBR(SSTOCK_B) TOMBR(SSTOCK_B);
CL: CRTSRVPGM SRVPGM(WEB_5TST/AS_SSTOCK) MODULE(WEB_5TST/AS_SSTOCK) SRCFILE(WEB_5TDV/QSRVSRC) SRCMBR(SSTOCK_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AS_SSTOCK));

-- AS_PRDINVT  (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AS_PRDINVT);
CL: DLTOBJ OBJ(WEB_5TST/AS_PRDINVT) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5TST/AS_PRDINVT) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AS_PRDINVT) TOMBR(AS_PRDINVT);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(PRDINVT_H) TOMBR(PRDINVT_H);
CL: CPYSRCF FROMFILE(ACS_5DEV/QSRVSRC) TOFILE(WEB_5TDV/QSRVSRC) FROMMBR(PRDINVT_B) TOMBR(PRDINVT_B);
CL: CRTSQLRPGI OBJ(WEB_5TST/AS_PRDINVT) SRCFILE(WEB_5TDV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CRTSRVPGM SRVPGM(WEB_5TST/AS_PRDINVT) MODULE(WEB_5TST/AS_PRDINVT) SRCFILE(WEB_5TDV/QSRVSRC) SRCMBR(PRDINVT_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AS_PRDINVT));
CL: GRTOBJAUT OBJ(WEB_5TST/AS_PRDINVT) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PRDINVT  (ready)
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_PRDINVT) TOMBR(AR_PRDINVT);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_PRDINVT) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_PRDINVT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_PRDINVT (ready)
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_PRDINVT) TOMBR(AC_PRDINVT);
CL: CRTBNDCL PGM(WEB_5TST/AC_PRDINVT) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_PRDINVT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_INVLOG (ready)
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_INVLOG) TOMBR(AR_INVLOG);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_INVLOG) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_INVLOG (ready)
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_INVLOG) TOMBR(AC_INVLOG);
CL: CRTBNDCL PGM(WEB_5TST/AC_INVLOG) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_INVLOG) TOMBR(TS_INVLOG);
CL: CRTBNDCL PGM(WEB_5TST/TS_INVLOG) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PSIREPT (ready)
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_PSIREPT) TOMBR(AR_PSIREPT);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_PSIREPT) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(WEB_5TST/AR_PSIREPT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);



--------------------------------------------------------------------------------
-- Deployment
--------------------------------------------------------------------------------

-- AC_PSIMIS  (ready)
CL: CPYSRCF FROMFILE(WEB_5TDV/QDDSSRC) TOFILE(WEB_5DEV/QDDSSRC) FROMMBR(AC_PSIMIS) TOMBR(AC_PSIMIS);
CL: CRTPRTF FILE(WEB_5OBJ/AC_PSIMIS) SRCFILE(WEB_5DEV/QDDSSRC) SRCMBR(AC_PSIMIS) IGCDTA(*N) IGCEXNCHR(*N) PAGESIZE(*N 198) IGCCHRRTT(*N) IGCCPI(*N) IGCSOSI(*N) IGCCDEFNT(*SYSVAL) REPLACE(*YES);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_PSIMIS) OBJTYPE(*ALL) USER(*PUBLIC) AUT(*ALL);

-- AR_INVRLOG  (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_INVRLOG);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_INVRLOG) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_INVRLOG) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_INVRLOG) TOMBR(AR_INVRLOG);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(INVRLOG_H) TOMBR(INVRLOG_H);
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(INVRLOG_B) TOMBR(INVRLOG_B);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_INVRLOG) SRCFILE(WEB_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AR_INVRLOG) MODULE(WEB_5OBJ/AR_INVRLOG) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(INVRLOG_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_INVRLOG));
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_INVRLOG) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AS_SSTOCK (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AS_SSTOCK);
CL: DLTOBJ OBJ(WEB_5OBJ/AS_SSTOCK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AS_SSTOCK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AS_SSTOCK) TOMBR(AS_SSTOCK);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(SSTOCK_H) TOMBR(SSTOCK_H);
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(SSTOCK_B) TOMBR(SSTOCK_B);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AS_SSTOCK) SRCFILE(WEB_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AS_SSTOCK) MODULE(WEB_5OBJ/AS_SSTOCK) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(SSTOCK_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AS_SSTOCK));

-- AS_PRDINVT  (ready)
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AS_PRDINVT);
CL: DLTOBJ OBJ(WEB_5OBJ/AS_PRDINVT) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AS_PRDINVT) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AS_PRDINVT) TOMBR(AS_PRDINVT);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(PRDINVT_H) TOMBR(PRDINVT_H);
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(PRDINVT_B) TOMBR(PRDINVT_B);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AS_PRDINVT) SRCFILE(WEB_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AS_PRDINVT) MODULE(WEB_5OBJ/AS_PRDINVT) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(PRDINVT_B) BNDDIR(K3SDIR);
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AS_PRDINVT));
CL: GRTOBJAUT OBJ(WEB_5OBJ/AS_PRDINVT) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PRDINVT  (ready)
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_PRDINVT) TOMBR(AR_PRDINVT);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_PRDINVT) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_PRDINVT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_PRDINVT (ready)
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_PRDINVT) TOMBR(AC_PRDINVT);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_PRDINVT) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_PRDINVT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_INVLOG (ready)
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_INVLOG) TOMBR(AR_INVLOG);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_INVLOG) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_INVLOG (ready)
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_INVLOG) TOMBR(AC_INVLOG);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_INVLOG) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_INVLOG) TOMBR(TS_INVLOG);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_INVLOG) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PSIREPT (ready)
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_PSIREPT) TOMBR(AR_PSIREPT);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_PSIREPT) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_PSIREPT) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- Set to current date
CL: CHGDTAARA DTAARA(WEB_5OBJ/AR_RELEASE *ALL) VALUE('012722');

--------------------------------------------------------------------------------
-- Hotfix to FTP site
--------------------------------------------------------------------------------

-- Clear save file
CL: CLRSAVF FILE(QGPL/k3shotfix);

-- Add objects to save file
CL: SAVOBJ OBJ(AC_PSIMIS AR_INVRLOG AS_SSTOCK AS_PRDINVT AR_PRDINVT AC_PRDINVT AR_INVLOG AC_INVLOG AR_PSIREPT) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/k3shotfix);

-- Upload savefile to Smartfile FTP site
--  (on Conan Dev)
FTP RMTSYS(K3S.SMARTFILE.COM)
> cd /R6_Deployment/Customer_Access
  250 "/R6_Deployment/Customer_Access" is the current directory.
> bin
  200 Type set to: Binary.
        > put r6objects
229 Entering extended passive mode (|||21344|).                            
125 Data connection already open. Transfer starting.                       
226 Transfer complete.                                                     
2356992 bytes transferred in 0.721 seconds. Transfer rate 3270.406 KB/sec. 
;



-- Hotfix to Conan DR

-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API objects to save file
CL: SAVOBJ OBJ(AR_INVLOG) LIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEANPUTDR;

-- on Conan DR...
CL: RSTOBJ OBJ(AR_INVLOG) SAVLIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK) RSTLIB(RES_5OBJ) ALWOBJDIF(*ALL) MBROPT(*ALL);

