-- GH842

-- 1. Name this file after its corresponding GitHub issue
-- 2. Search for <api_name> and replace with API program name (shift + command + H)
-- 3. Remove service program compile commands if not used
-- 4. Search for <api_text> and replace with API text
-- 5. Search for <api_test_text> and replace with API test text
-- 6. If service programs are involved...
--    A. Search for <srvpgm_name> and replace with service program name
--    B. Search for <srvpgm_text> and replace with service program text





--==============================================================================
-- In Development
--==============================================================================

    --------------------------------------------------------------------------------
    -- Table(s)
    --------------------------------------------------------------------------------

    -- K_SPLWORK
    DROP TABLE ACS_5MOD.K_SPLWORK;
    CREATE TABLE ACS_5MOD.K_SPLWORK (
      SW_COMP Char(1) CCSID 37 NOT NULL DEFAULT '',
      SW_BUYR Char(5) CCSID 37 NOT NULL DEFAULT '',
      SW_LOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      SW_SUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      SW_SUPLSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      SW_USER Char(10) CCSID 37 NOT NULL DEFAULT ''
    )
    RCDFMT RK_SPLWORK;

    LABEL ON TABLE ACS_5MOD.K_SPLWORK IS 'Work File - Suppliers';
    LABEL ON COLUMN ACS_5MOD.K_SPLWORK
    (
        SW_COMP IS 'Company             ID' ,
        SW_BUYR IS 'Buy                 group               ID' ,
    	SW_LOCN IS 'Location            ID' ,
    	SW_SUPL IS 'Supplier            ID' ,
    	SW_SUPLSUB IS 'Sub                 supplier            ID' ,
    	SW_USER IS 'User                who called          API' 
    );
    LABEL ON COLUMN ACS_5MOD.K_SPLWORK (
        SW_COMP TEXT IS 'Company ID',
    	SW_BUYR TEXT IS 'Buy group ID',
    	SW_LOCN TEXT IS 'Location ID',
    	SW_SUPL TEXT IS 'Supplier ID',
    	SW_SUPLSUB TEXT IS 'Sub supplier ID',
    	SW_USER TEXT IS 'Supplier user system'
    );
    select * from acs_5mod.k_splwork;

    -- K_PRDWORK
    DROP TABLE ACS_5MOD.K_PRDWORK;
    CREATE TABLE ACS_5MOD.K_PRDWORK (
      RW_COMP Char(1) CCSID 37 NOT NULL DEFAULT '',
      RW_BUYR Char(5) CCSID 37 NOT NULL DEFAULT '',
      RW_LOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      RW_SUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      RW_SUPLSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      RW_PROD Char(25) CCSID 37 NOT NULL DEFAULT '',
      RW_USER Char(10) CCSID 37 NOT NULL DEFAULT '',
      RW_CMBLOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      RW_CMBSUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      RW_CMBSUB Char(10) CCSID 37 NOT NULL DEFAULT ''
    )
    RCDFMT RK_PRDWORK;

    LABEL ON TABLE ACS_5MOD.K_PRDWORK IS 'Work File - Products';
    LABEL ON COLUMN ACS_5MOD.K_PRDWORK
    (
        RW_COMP IS 'Company             ID',
        RW_BUYR IS 'Buy                 group               ID',
    	RW_LOCN IS 'Location            ID',
    	RW_SUPL IS 'Supplier            ID',
    	RW_SUPLSUB IS 'Sub                 supplier            ID',
        RW_PROD IS 'Product             ID',
    	RW_USER IS 'User                who called          API',
        RW_CMBLOCN IS 'Combined         Location',
        RW_CMBSUPL IS 'Combined         Supplier',
        RW_CMBSUB IS 'Combined          Sub Supplier'
    );
    LABEL ON COLUMN ACS_5MOD.K_PRDWORK (
        RW_COMP TEXT IS 'Company ID',
    	RW_BUYR TEXT IS 'Buy group ID',
    	RW_LOCN TEXT IS 'Location ID',
    	RW_SUPL TEXT IS 'Supplier ID',
    	RW_SUPLSUB TEXT IS 'Sub supplier ID',
        RW_PROD TEXT IS 'Product ID',
    	RW_USER TEXT IS 'User who called API',
        RW_CMBLOCN TEXT IS 'Combined Location',
        RW_CMBSUPL TEXT IS 'Combined Supplier',
        RW_CMBSUB TEXT IS 'Combined Sub Supplier'
    );
    select * from acs_5mod.k_prdwork;
    
    -- K_PROWORK
    DROP TABLE ACS_5MOD.K_PROWORK;
    CREATE TABLE ACS_5MOD.K_PROWORK (
      OW_COMP Char(1) CCSID 37 NOT NULL DEFAULT '',
      OW_BUYR Char(5) CCSID 37 NOT NULL DEFAULT '',
      OW_LOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      OW_SUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      OW_SUPLSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      OW_SOQSEQN DECIMAL(5, 0) NOT NULL DEFAULT 0,
      OW_PROD Char(25) CCSID 37 NOT NULL DEFAULT '',
      OW_CMBLOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      OW_CMBSUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      OW_CMBSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      OW_USER Char(10) CCSID 37 NOT NULL DEFAULT ''
    )
    RCDFMT RK_PROWORK;

    LABEL ON TABLE ACS_5MOD.K_PROWORK IS 'Work File - Products';
    LABEL ON COLUMN ACS_5MOD.K_PROWORK
    (
        OW_COMP IS 'Company             ID',
        OW_BUYR IS 'Buy                 group               ID',
    	OW_LOCN IS 'Location            ID',
    	OW_SUPL IS 'Supplier            ID',
    	OW_SUPLSUB IS 'Sub                 supplier            ID',
        OW_SOQSEQN IS 'Suggested           order               seq #',
        OW_PROD IS 'Product             ID',
        OW_CMBLOCN IS 'Combined          location',
        OW_CMBSUPL IS 'Combined          supplier',
        OW_CMBSUB IS 'Combined           sub supplier',
    	OW_USER IS 'User                who called          API'
    );
    LABEL ON COLUMN ACS_5MOD.K_PROWORK (
        OW_COMP TEXT IS 'Company ID',
    	OW_BUYR TEXT IS 'Buy group ID',
    	OW_LOCN TEXT IS 'Location ID',
    	OW_SUPL TEXT IS 'Supplier ID',
    	OW_SUPLSUB TEXT IS 'Sub supplier ID',
        OW_SOQSEQN TEXT IS 'Suggested order seq #',
        OW_PROD TEXT IS 'Product ID',
        OW_CMBLOCN TEXT IS 'Combined Location',
        OW_CMBSUPL TEXT IS 'Combined Supplier',
        OW_CMBSUB TEXT IS 'Combined Sub Supplier',
    	OW_USER TEXT IS 'User who called API'
    );
    select * from acs_5mod.k_prowork;
    
    
    -- K_ALLWORK
    DROP TABLE ACS_5MOD.K_ALLWORK;
    CREATE TABLE ACS_5MOD.K_ALLWORK (
      AW_COMP Char(1) CCSID 37 NOT NULL DEFAULT '',
      AW_BUYR Char(5) CCSID 37 NOT NULL DEFAULT '',
      AW_LOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      AW_SUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      AW_SUPLSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      AW_PROD Char(25) CCSID 37 NOT NULL DEFAULT '',
      AW_USER Char(10) CCSID 37 NOT NULL DEFAULT '',
      AW_CMBLOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      AW_CMBSUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      AW_CMBSUB Char(10) CCSID 37 NOT NULL DEFAULT ''
    )
    RCDFMT RK_ALLWORK;

    LABEL ON TABLE ACS_5MOD.K_ALLWORK IS 'Work File - ALL';
    LABEL ON COLUMN ACS_5MOD.K_ALLWORK
    (
        AW_COMP IS 'Company             ID',
        AW_BUYR IS 'Buy                 group               ID',
    	AW_LOCN IS 'Location            ID',
    	AW_SUPL IS 'Supplier            ID',
    	AW_SUPLSUB IS 'Sub                 supplier            ID',
        AW_PROD IS 'Product             ID',
    	AW_USER IS 'User                who called          API',
        AW_CMBLOCN IS 'Combined                 Location',
        AW_CMBSUPL IS 'Combined                 Supplier',
        AW_CMBSUB IS 'Combined                  Sub Supplier'
    );
    LABEL ON COLUMN ACS_5MOD.K_ALLWORK (
        AW_COMP TEXT IS 'Company ID',
        AW_BUYR TEXT IS 'Buy group ID',
    	AW_LOCN TEXT IS 'Location ID',
    	AW_SUPL TEXT IS 'Supplier ID',
    	AW_SUPLSUB TEXT IS 'Sub supplier ID',
        AW_PROD TEXT IS 'Product ID',
    	AW_USER TEXT IS 'User who called API',
        AW_CMBLOCN TEXT IS 'Combined Location',
        AW_CMBSUPL TEXT IS 'Combined Supplier',
        AW_CMBSUB TEXT IS 'Combined Sub Supplier'
    );
    select * from acs_5mod.k_allwork;
    
    
    
-- Service Program(s)

-- AR_SPLWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_SPLWORK);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_SPLWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_SPLWORK) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_SPLWORK) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AR_SPLWORK) MODULE(ACS_5OBJ/AR_SPLWORK) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(SPLWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_SPLWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_SPLWORK));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_SPLWORK) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PRDWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_PRDWORK);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_PRDWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_PRDWORK) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_PRDWORK) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AR_PRDWORK) MODULE(ACS_5OBJ/AR_PRDWORK) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(PRDWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_PRDWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_PRDWORK));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_PRDWORK) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PROWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_PROWORK);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_PROWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_PROWORK) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_PROWORK) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AR_PROWORK) MODULE(ACS_5OBJ/AR_PROWORK) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(PROWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_PROWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_PROWORK));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_PROWORK) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AR_ALLWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_ALLWORK);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_ALLWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_ALLWORK) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_ALLWORK) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AR_ALLWORK) MODULE(ACS_5OBJ/AR_ALLWORK) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(ALLWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_ALLWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_ALLWORK));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_ALLWORK) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);


-- API Program(s)
-- CSPWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CSPWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_SPLWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CSPWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_SPLWORK    AR_SPLWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CSPWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CSPWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CPRWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPRWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_PRDWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPRWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_PRDWORK    AR_PRDWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPRWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPRWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CPOWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPOWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_PROWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPOWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_PROWORK    AR_PROWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPOWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPOWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CALWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CALWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_ALLWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CALWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_ALLWORK    AR_ALLWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CALWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CALWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DPRWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_DPRWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_PRDWORK rows by user');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_DPRWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_PRDWORK rows by user     AR_DPRWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_DPRWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DPRWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DALWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_DALWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_ALLWORK rows by user');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_DALWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_ALLWORK rows by user     AR_DALWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_DALWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DALWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DSPWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_DSPWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_SPLWORK rows by user');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_DSPWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_SPLWORK rows by user     AR_DSPWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_DSPWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DSPWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DPOWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_DPOWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_PROWORK rows by user');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_DPOWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_PROWORK rows by user     AR_DPOWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_DPOWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DPOWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Integrated Testing Environment
--------------------------------------------------------------------------------


    --------------------------------------------------------------------------------
    -- Table(s)
    --------------------------------------------------------------------------------

    -- K_SPLWORK
    DROP TABLE WEB_5MOD.K_SPLWORK;
    CREATE TABLE WEB_5MOD.K_SPLWORK (
      SW_COMP Char(1) CCSID 37 NOT NULL DEFAULT '',
      SW_BUYR Char(5) CCSID 37 NOT NULL DEFAULT '',
      SW_LOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      SW_SUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      SW_SUPLSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      SW_USER Char(10) CCSID 37 NOT NULL DEFAULT ''
    )
    RCDFMT RK_SPLWORK;

    LABEL ON TABLE WEB_5MOD.K_SPLWORK IS 'Work File - Suppliers';
    LABEL ON COLUMN WEB_5MOD.K_SPLWORK
    (
        SW_COMP IS 'Company             ID' ,
        SW_BUYR IS 'Buy                 group               ID' ,
    	SW_LOCN IS 'Location            ID' ,
    	SW_SUPL IS 'Supplier            ID' ,
    	SW_SUPLSUB IS 'Sub                 supplier            ID' ,
    	SW_USER IS 'User                who called          API' 
    );
    LABEL ON COLUMN WEB_5MOD.K_SPLWORK (
        SW_COMP TEXT IS 'Company ID',
    	SW_BUYR TEXT IS 'Buy group ID',
    	SW_LOCN TEXT IS 'Location ID',
    	SW_SUPL TEXT IS 'Supplier ID',
    	SW_SUPLSUB TEXT IS 'Sub supplier ID',
    	SW_USER TEXT IS 'Supplier user system'
    );
    select * from WEB_5MOD.k_splwork;

    -- K_PRDWORK
    DROP TABLE WEB_5MOD.K_PRDWORK;
    CREATE TABLE WEB_5MOD.K_PRDWORK (
      RW_COMP Char(1) CCSID 37 NOT NULL DEFAULT '',
      RW_BUYR Char(5) CCSID 37 NOT NULL DEFAULT '',
      RW_LOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      RW_SUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      RW_SUPLSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      RW_PROD Char(25) CCSID 37 NOT NULL DEFAULT '',
      RW_USER Char(10) CCSID 37 NOT NULL DEFAULT '',
      RW_CMBLOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      RW_CMBSUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      RW_CMBSUB Char(10) CCSID 37 NOT NULL DEFAULT ''
    )
    RCDFMT RK_PRDWORK;

    LABEL ON TABLE WEB_5MOD.K_PRDWORK IS 'Work File - Products';
    LABEL ON COLUMN WEB_5MOD.K_PRDWORK
    (
        RW_COMP IS 'Company             ID',
        RW_BUYR IS 'Buy                 group               ID',
    	RW_LOCN IS 'Location            ID',
    	RW_SUPL IS 'Supplier            ID',
    	RW_SUPLSUB IS 'Sub                 supplier            ID',
        RW_PROD IS 'Product             ID',
    	RW_USER IS 'User                who called          API',
        RW_CMBSUPL IS 'Combined          supplier',
        RW_CMBSUB IS 'Combined           sub supplier',
    	RW_USER IS 'User                who called          API'
    );
    LABEL ON COLUMN WEB_5MOD.K_PRDWORK (
        RW_COMP TEXT IS 'Company ID',
    	RW_BUYR TEXT IS 'Buy group ID',
    	RW_LOCN TEXT IS 'Location ID',
    	RW_SUPL TEXT IS 'Supplier ID',
    	RW_SUPLSUB TEXT IS 'Sub supplier ID',
        RW_PROD TEXT IS 'Product ID',
    	RW_USER TEXT IS 'User who called API',
        RW_CMBLOCN TEXT IS 'Combined Location',
        RW_CMBSUPL TEXT IS 'Combined Supplier',
        RW_CMBSUB TEXT IS 'Combined Sub Supplier'
    );
    select * from WEB_5MOD.k_prdwork;
    
    -- K_PROWORK
    DROP TABLE WEB_5MOD.K_PROWORK;
    CREATE TABLE WEB_5MOD.K_PROWORK (
      OW_COMP Char(1) CCSID 37 NOT NULL DEFAULT '',
      OW_BUYR Char(5) CCSID 37 NOT NULL DEFAULT '',
      OW_LOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      OW_SUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      OW_SUPLSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      OW_SOQSEQN DECIMAL(5, 0) NOT NULL DEFAULT 0,
      OW_PROD Char(25) CCSID 37 NOT NULL DEFAULT '',
      OW_CMBLOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      OW_CMBSUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      OW_CMBSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      OW_USER Char(10) CCSID 37 NOT NULL DEFAULT ''
    )
    RCDFMT RK_PROWORK;

    LABEL ON TABLE WEB_5MOD.K_PROWORK IS 'Work File - Products';
    LABEL ON COLUMN WEB_5MOD.K_PROWORK
    (
        OW_COMP IS 'Company             ID',
        OW_BUYR IS 'Buy                 group               ID',
    	OW_LOCN IS 'Location            ID',
    	OW_SUPL IS 'Supplier            ID',
    	OW_SUPLSUB IS 'Sub                 supplier            ID',
        OW_SOQSEQN IS 'Suggested           order               seq #',
        OW_PROD IS 'Product             ID',
        OW_CMBLOCN IS 'Combined          location',
        OW_CMBSUPL IS 'Combined          supplier',
        OW_CMBSUB IS 'Combined           sub supplier',
    	OW_USER IS 'User                who called          API'
    );
    LABEL ON COLUMN WEB_5MOD.K_PROWORK (
        OW_COMP TEXT IS 'Company ID',
    	OW_BUYR TEXT IS 'Buy group ID',
    	OW_LOCN TEXT IS 'Location ID',
    	OW_SUPL TEXT IS 'Supplier ID',
    	OW_SUPLSUB TEXT IS 'Sub supplier ID',
        OW_SOQSEQN TEXT IS 'Suggested order seq #',
        OW_PROD TEXT IS 'Product ID',
        OW_CMBLOCN TEXT IS 'Combined Location',
        OW_CMBSUPL TEXT IS 'Combined Supplier',
        OW_CMBSUB TEXT IS 'Combined Sub Supplier',
    	OW_USER TEXT IS 'User who called API'
    );
    select * from WEB_5MOD.k_prowork;
    
    
    -- K_ALLWORK
    DROP TABLE WEB_5MOD.K_ALLWORK;
    CREATE TABLE WEB_5MOD.K_ALLWORK (
      AW_COMP Char(1) CCSID 37 NOT NULL DEFAULT '',
      AW_BUYR Char(5) CCSID 37 NOT NULL DEFAULT '',
      AW_LOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      AW_SUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      AW_SUPLSUB Char(10) CCSID 37 NOT NULL DEFAULT '',
      AW_PROD Char(25) CCSID 37 NOT NULL DEFAULT '',
      AW_USER Char(10) CCSID 37 NOT NULL DEFAULT '',
      AW_CMBLOCN Char(5) CCSID 37 NOT NULL DEFAULT '',
      AW_CMBSUPL Char(10) CCSID 37 NOT NULL DEFAULT '',
      AW_CMBSUB Char(10) CCSID 37 NOT NULL DEFAULT ''
    )
    RCDFMT RK_ALLWORK;

    LABEL ON TABLE WEB_5MOD.K_ALLWORK IS 'Work File - ALL';
    LABEL ON COLUMN WEB_5MOD.K_ALLWORK
    (
        AW_COMP IS 'Company             ID',
        AW_BUYR IS 'Buy                 group               ID',
    	AW_LOCN IS 'Location            ID',
    	AW_SUPL IS 'Supplier            ID',
    	AW_SUPLSUB IS 'Sub                 supplier            ID',
        AW_PROD IS 'Product             ID',
    	AW_USER IS 'User                who called          API',
        AW_CMBLOCN IS 'Combined                 Location',
        AW_CMBSUPL IS 'Combined                 Supplier',
        AW_CMBSUB IS 'Combined                  Sub Supplier'
    );
    LABEL ON COLUMN WEB_5MOD.K_ALLWORK (
        AW_COMP TEXT IS 'Company ID',
        AW_BUYR TEXT IS 'Buy group ID',
    	AW_LOCN TEXT IS 'Location ID',
    	AW_SUPL TEXT IS 'Supplier ID',
    	AW_SUPLSUB TEXT IS 'Sub supplier ID',
        AW_PROD TEXT IS 'Product ID',
    	AW_USER TEXT IS 'User who called API',
        AW_CMBLOCN TEXT IS 'Combined Location',
        AW_CMBSUPL TEXT IS 'Combined Supplier',
        AW_CMBSUB TEXT IS 'Combined Sub Supplier'
    );
    select * from WEB_5MOD.k_allwork;
    

-- Service Program(s)

-- AR_SPLWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_SPLWORK);
CL: DLTOBJ OBJ(WEB_5TST/AR_SPLWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5TST/AR_SPLWORK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_SPLWORK) TOMBR(AR_SPLWORK);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(SPLWORK_H) TOMBR(SPLWORK_H);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_SPLWORK) SRCFILE(WEB_5TDV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CPYSRCF FROMFILE(ACS_5DEV/QSRVSRC) TOFILE(WEB_5TDV/QSRVSRC) FROMMBR(SPLWORK_B) TOMBR(SPLWORK_B);
CL: CRTSRVPGM SRVPGM(WEB_5TST/AR_SPLWORK) MODULE(WEB_5TST/AR_SPLWORK) SRCFILE(WEB_5TDV/QSRVSRC) SRCMBR(SPLWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_SPLWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_SPLWORK));

-- AR_PRDWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_PRDWORK);
CL: DLTOBJ OBJ(WEB_5TST/AR_PRDWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5TST/AR_PRDWORK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_PRDWORK) TOMBR(AR_PRDWORK);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(PRDWORK_H) TOMBR(PRDWORK_H);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_PRDWORK) SRCFILE(WEB_5TDV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CPYSRCF FROMFILE(ACS_5DEV/QSRVSRC) TOFILE(WEB_5TDV/QSRVSRC) FROMMBR(PRDWORK_B) TOMBR(PRDWORK_B);
CL: CRTSRVPGM SRVPGM(WEB_5TST/AR_PRDWORK) MODULE(WEB_5TST/AR_PRDWORK) SRCFILE(WEB_5TDV/QSRVSRC) SRCMBR(PRDWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_PRDWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_PRDWORK));

-- AR_PROWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_PROWORK);
CL: DLTOBJ OBJ(WEB_5TST/AR_PROWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5TST/AR_PROWORK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_PROWORK) TOMBR(AR_PROWORK);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(PROWORK_H) TOMBR(PROWORK_H);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_PROWORK) SRCFILE(WEB_5TDV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CPYSRCF FROMFILE(ACS_5DEV/QSRVSRC) TOFILE(WEB_5TDV/QSRVSRC) FROMMBR(PROWORK_B) TOMBR(PROWORK_B);
CL: CRTSRVPGM SRVPGM(WEB_5TST/AR_PROWORK) MODULE(WEB_5TST/AR_PROWORK) SRCFILE(WEB_5TDV/QSRVSRC) SRCMBR(PROWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_PROWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_PROWORK));

-- AR_ALLWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_ALLWORK);
CL: DLTOBJ OBJ(WEB_5TST/AR_ALLWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5TST/AR_ALLWORK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_ALLWORK) TOMBR(AR_ALLWORK);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(ALLWORK_H) TOMBR(ALLWORK_H);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_ALLWORK) SRCFILE(WEB_5TDV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CPYSRCF FROMFILE(ACS_5DEV/QSRVSRC) TOFILE(WEB_5TDV/QSRVSRC) FROMMBR(ALLWORK_B) TOMBR(ALLWORK_B);
CL: CRTSRVPGM SRVPGM(WEB_5TST/AR_ALLWORK) MODULE(WEB_5TST/AR_ALLWORK) SRCFILE(WEB_5TDV/QSRVSRC) SRCMBR(ALLWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_ALLWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_ALLWORK));


-- API Program(s)
-- CSPWORK
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CSPWORK) TOMBR(AR_CSPWORK);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CSPWORK) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_SPLWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CSPWORK) TOMBR(AC_CSPWORK);
CL: CRTBNDCL PGM(WEB_5TST/AC_CSPWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_SPLWORK    AR_SPLWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CSPWORK) TOMBR(TS_CSPWORK);
CL: CRTBNDCL PGM(WEB_5TST/TS_CSPWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CSPWORK');
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CPRWORK
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPRWORK) TOMBR(AR_CPRWORK);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPRWORK) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_PRDWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPRWORK) TOMBR(AC_CPRWORK);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPRWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_PRDWORK    AR_PRDWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPRWORK) TOMBR(TS_CPRWORK);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPRWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPRWORK');
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CPOWORK
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CPOWORK) TOMBR(AR_CPOWORK);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CPOWORK) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_PROWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CPOWORK) TOMBR(AC_CPOWORK);
CL: CRTBNDCL PGM(WEB_5TST/AC_CPOWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_PROWORK    AR_PROWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CPOWORK) TOMBR(TS_CPOWORK);
CL: CRTBNDCL PGM(WEB_5TST/TS_CPOWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPOWORK');
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CALWORK
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_CALWORK) TOMBR(AR_CALWORK);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_CALWORK) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_ALLWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_CALWORK) TOMBR(AC_CALWORK);
CL: CRTBNDCL PGM(WEB_5TST/AC_CALWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_ALLWORK    AR_ALLWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_CALWORK) TOMBR(TS_CALWORK);
CL: CRTBNDCL PGM(WEB_5TST/TS_CALWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CALWORK');
CL: GRTOBJAUT OBJ(WEB_5TST/AR_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DPRWORK
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_DPRWORK) TOMBR(AR_DPRWORK);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_DPRWORK) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_PRDWORK rows by user');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_DPRWORK) TOMBR(AC_DPRWORK);
CL: CRTBNDCL PGM(WEB_5TST/AC_DPRWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_PRDWORK rows by user     AR_DPRWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_DPRWORK) TOMBR(TS_DPRWORK);
CL: CRTBNDCL PGM(WEB_5TST/TS_DPRWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DPRWORK');
CL: GRTOBJAUT OBJ(WEB_5TST/AR_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DALWORK
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_DALWORK) TOMBR(AR_DALWORK);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_DALWORK) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_ALLWORK rows by user');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_DALWORK) TOMBR(AC_DALWORK);
CL: CRTBNDCL PGM(WEB_5TST/AC_DALWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_ALLWORK rows by user     AR_DALWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_DALWORK) TOMBR(TS_DALWORK);
CL: CRTBNDCL PGM(WEB_5TST/TS_DALWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DALWORK');
CL: GRTOBJAUT OBJ(WEB_5TST/AR_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DSPWORK
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_DSPWORK) TOMBR(AR_DSPWORK);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_DSPWORK) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_SPLWORK rows by user');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_DSPWORK) TOMBR(AC_DSPWORK);
CL: CRTBNDCL PGM(WEB_5TST/AC_DSPWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_SPLWORK rows by user     AR_DSPWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_DSPWORK) TOMBR(TS_DSPWORK);
CL: CRTBNDCL PGM(WEB_5TST/TS_DSPWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DSPWORK');
CL: GRTOBJAUT OBJ(WEB_5TST/AR_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DPOWORK
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_DPOWORK) TOMBR(AR_DPOWORK);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_DPOWORK) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_PROWORK rows by user');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_DPOWORK) TOMBR(AC_DPOWORK);
CL: CRTBNDCL PGM(WEB_5TST/AC_DPOWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_PROWORK rows by user     AR_DPOWORK');
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(TS_DPOWORK) TOMBR(TS_DPOWORK);
CL: CRTBNDCL PGM(WEB_5TST/TS_DPOWORK) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DPOWORK');
CL: GRTOBJAUT OBJ(WEB_5TST/AR_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/TS_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Deployment
--------------------------------------------------------------------------------

-- Service Program(s)

-- AR_SPLWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_SPLWORK);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_SPLWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_SPLWORK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_SPLWORK) TOMBR(AR_SPLWORK);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(SPLWORK_H) TOMBR(SPLWORK_H);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_SPLWORK) SRCFILE(WEB_5DEV/QRPGLESRC) OBJTYPE(*MODULE) TGTRLS(V7R2M0);
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(SPLWORK_B) TOMBR(SPLWORK_B);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AR_SPLWORK) MODULE(WEB_5OBJ/AR_SPLWORK) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(SPLWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_SPLWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_SPLWORK));

-- AR_PRDWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_PRDWORK);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_PRDWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_PRDWORK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_PRDWORK) TOMBR(AR_PRDWORK);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(PRDWORK_H) TOMBR(PRDWORK_H);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_PRDWORK) SRCFILE(WEB_5DEV/QRPGLESRC) OBJTYPE(*MODULE) TGTRLS(V7R2M0);
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(PRDWORK_B) TOMBR(PRDWORK_B);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AR_PRDWORK) MODULE(WEB_5OBJ/AR_PRDWORK) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(PRDWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_PRDWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_PRDWORK));

-- AR_PROWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_PROWORK);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_PROWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_PROWORK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_PROWORK) TOMBR(AR_PROWORK);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(PROWORK_H) TOMBR(PROWORK_H);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_PROWORK) SRCFILE(WEB_5DEV/QRPGLESRC) OBJTYPE(*MODULE) TGTRLS(V7R2M0);
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(PROWORK_B) TOMBR(PROWORK_B);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AR_PROWORK) MODULE(WEB_5OBJ/AR_PROWORK) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(PROWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_PROWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_PROWORK));

-- AR_ALLWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_ALLWORK);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_ALLWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(WEB_5OBJ/AR_ALLWORK) OBJTYPE(*MODULE);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_ALLWORK) TOMBR(AR_ALLWORK);
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(ALLWORK_H) TOMBR(ALLWORK_H);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_ALLWORK) SRCFILE(WEB_5DEV/QRPGLESRC) OBJTYPE(*MODULE) TGTRLS(V7R2M0);
CL: CPYSRCF FROMFILE(WEB_5TDV/QSRVSRC) TOFILE(WEB_5DEV/QSRVSRC) FROMMBR(ALLWORK_B) TOMBR(ALLWORK_B);
CL: CRTSRVPGM SRVPGM(WEB_5OBJ/AR_ALLWORK) MODULE(WEB_5OBJ/AR_ALLWORK) SRCFILE(WEB_5DEV/QSRVSRC) SRCMBR(ALLWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_ALLWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_ALLWORK));




-- CSPWORK
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CSPWORK) TOMBR(AR_CSPWORK);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CSPWORK) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_SPLWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CSPWORK) TOMBR(AC_CSPWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CSPWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Add/remove entry in K_SPLWORK    AR_SPLWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CSPWORK) TOMBR(TS_CSPWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CSPWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_CSPWORK');
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CPRWORK
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPRWORK) TOMBR(AR_CPRWORK);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPRWORK) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_PRDWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPRWORK) TOMBR(AC_CPRWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPRWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Add/remove entry in K_PRDWORK    AR_PRDWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPRWORK) TOMBR(TS_CPRWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPRWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_CPRWORK');
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CPOWORK
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CPOWORK) TOMBR(AR_CPOWORK);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CPOWORK) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_PROWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CPOWORK) TOMBR(AC_CPOWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CPOWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Add/remove entry in K_PROWORK    AR_PROWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CPOWORK) TOMBR(TS_CPOWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CPOWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_CPOWORK');
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- CALWORK
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_CALWORK) TOMBR(AR_CALWORK);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_CALWORK) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_ALLWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_CALWORK) TOMBR(AC_CALWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_CALWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Add/remove entry in K_ALLWORK    AR_ALLWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_CALWORK) TOMBR(TS_CALWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_CALWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_CALWORK');
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DPRWORK
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_DPRWORK) TOMBR(AR_DPRWORK);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_DPRWORK) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Clear K_PRDWORK rows by user');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_DPRWORK) TOMBR(AC_DPRWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_DPRWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Clear K_PRDWORK rows by user     AR_DPRWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_DPRWORK) TOMBR(TS_DPRWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_DPRWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_DPRWORK');
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DALWORK
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_DALWORK) TOMBR(AR_DALWORK);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_DALWORK) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Clear K_ALLWORK rows by user');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_DALWORK) TOMBR(AC_DALWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_DALWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Clear K_ALLWORK rows by user     AR_DALWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_DALWORK) TOMBR(TS_DALWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_DALWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_DALWORK');
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DSPWORK
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_DSPWORK) TOMBR(AR_DSPWORK);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_DSPWORK) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Clear K_SPLWORK rows by user');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_DSPWORK) TOMBR(AC_DSPWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_DSPWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Clear K_SPLWORK rows by user     AR_DSPWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_DSPWORK) TOMBR(TS_DSPWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_DSPWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_DSPWORK');
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_DSPWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DPOWORK
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_DPOWORK) TOMBR(AR_DPOWORK);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_DPOWORK) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) TGTRLS(V7R2M0) TEXT('Web - Clear K_PROWORK rows by user');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(AC_DPOWORK) TOMBR(AC_DPOWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/AC_DPOWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Web - Clear K_PROWORK rows by user     AR_DPOWORK');
CL: CPYSRCF FROMFILE(WEB_5TDV/QCLLESRC) TOFILE(WEB_5DEV/QCLLESRC) FROMMBR(TS_DPOWORK) TOMBR(TS_DPOWORK);
CL: CRTBNDCL PGM(WEB_5OBJ/TS_DPOWORK) SRCFILE(WEB_5DEV/QCLLESRC) OPTION(*EVENTF) TEXT('Testing AC_DPOWORK');
CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/AC_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5OBJ/TS_DPOWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

--------------------------------------------------------------------------------
-- Hotfix to self-hosted
--------------------------------------------------------------------------------

-- Clear save file
CL: CLRSAVF FILE(QGPL/r6objects);

-- Add objects to save file
CL: SAVOBJ OBJ(AR_<srvpgm_name> AC_<api_name> AR_<api_name> TS_<api_name>) LIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/r6objects);

-- Upload savefile to Smartfile FTP site
--  (on Conan Dev)
FTP RMTSYS(K3S.SMARTFILE.COM)
> cd /R6_Deployment/Customer_Access
  250 "/R6_Deployment/Customer_Access" is the current directory.
> bin
  200 Type set to: Binary.
> put r6objects                                                        
229 Entering extended passive mode (|||21344|).                            
125 Data connection already open. Transfer starting.                       
226 Transfer complete.                                                     
2356992 bytes transferred in 0.721 seconds. Transfer rate 3270.406 KB/sec. ;


--------------------------------------------------------------------------------
-- Hotfix to hosted
--------------------------------------------------------------------------------
-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API object in error to save file
delete from WEB_5MOD.K_PRDWORK;
delete from WEB_5MOD.K_ALLWORK;
CL: SAVOBJ OBJ(K_PRDWORK K_ALLWORK) LIB(WEB_5MOD) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);
CL: SAVOBJ OBJ(AR_PRDWORK AR_ALLWORK AR_CPRWORK AC_CPRWORK AR_CALWORK AC_CALWORK) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEAN_PUTL;

-- on Leno...

-- Restore the save file objects to library DMO
CL: RSTOBJ OBJ(*ALL) SAVLIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK) RSTLIB(DMO_5OBJ) ALWOBJDIF(*ALL) MBROPT(*ALL);


--------------------------------------------------------------------------------
-- Hotfix to self-hosted
--------------------------------------------------------------------------------
-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API object in error to save file
CL: SAVOBJ OBJ(AR_PUSORDR AR_LTMAPOR) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEAN_PUTL;


--------------------------------------------------------------------------------
-- Hotfix to Conan DR
--------------------------------------------------------------------------------

-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API objects to save file
CL: SAVOBJ OBJ(AR_PUSORDR AR_LTMAPOR) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEANPUTDR;

