-- GH848

CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_PRDWORK) TOMBR(AR_PRDWORK);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(PRDWORK_H) TOMBR(PRDWORK_H);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_ALLWORK) TOMBR(AR_ALLWORK);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(ALLWORK_H) TOMBR(ALLWORK_H);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CPRWORK) TOMBR(AR_CPRWORK);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_DPRWORK) TOMBR(AR_DPRWORK);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_CALWORK) TOMBR(AR_CALWORK);
CL: CPYSRCF FROMFILE(WEB_5DEV/QRPGLESRC) TOFILE(ACS_5DEV/QRPGLESRC) FROMMBR(AR_DALWORK) TOMBR(AR_DALWORK);

CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CPRWORK) TOMBR(AC_CPRWORK);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_DPRWORK) TOMBR(AC_DPRWORK);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_CALWORK) TOMBR(AC_CALWORK);
CL: CPYSRCF FROMFILE(WEB_5DEV/QCLLESRC) TOFILE(ACS_5DEV/QCLLESRC) FROMMBR(AC_DALWORK) TOMBR(AC_DALWORK);


--------------------------------------------------------------------------------
-- In Development
--------------------------------------------------------------------------------

-------------------------------------------------------
-- Run During Development
-------------------------------------------------------

-- https://www.ibm.com/docs/en/i/7.2?topic=cssiira-example-dynamic-sql-in-ile-rpg-application-that-uses-sql

-- AR_PRDWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_PRDWORK);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_PRDWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_PRDWORK) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_PRDWORK) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AR_PRDWORK) MODULE(ACS_5OBJ/AR_PRDWORK) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(PRDWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_PRDWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_PRDWORK));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_PRDWORK) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);

-- AR_ALLWORK
CL: RMVBNDDIRE BNDDIR(K3SDIR) OBJ(AR_ALLWORK);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_ALLWORK) OBJTYPE(*SRVPGM);
CL: DLTOBJ OBJ(ACS_5OBJ/AR_ALLWORK) OBJTYPE(*MODULE);
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_ALLWORK) SRCFILE(ACS_5DEV/QRPGLESRC) OBJTYPE(*MODULE) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);
CL: CRTSRVPGM SRVPGM(ACS_5OBJ/AR_ALLWORK) MODULE(ACS_5OBJ/AR_ALLWORK) SRCFILE(ACS_5DEV/QSRVSRC) SRCMBR(ALLWORK_B) BNDDIR(K3SDIR) TEXT('Web-Service Prog. 2 Insert/Delete/Update K_ALLWORK');
CL: ADDBNDDIRE BNDDIR(K3SDIR) OBJ((AR_ALLWORK));
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_ALLWORK) OBJTYPE(*SRVPGM) USER(*PUBLIC) AUT(*ALL);



-- CPRWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CPRWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_PRDWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CPRWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_PRDWORK    AR_PRDWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CPRWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CPRWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- CALWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_CALWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Add/remove entry in K_ALLWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_CALWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Add/remove entry in K_ALLWORK    AR_ALLWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_CALWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_CALWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_CALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- DPRWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_DPRWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_PRDWORK rows by user');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_DPRWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_PRDWORK rows by user     AR_DPRWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_DPRWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DPRWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_DPRWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- DALWORK
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_DALWORK) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0) TEXT('Web - Clear K_ALLWORK rows by user');
CL: CRTBNDCL PGM(ACS_5OBJ/AC_DALWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Web - Clear K_ALLWORK rows by user     AR_DALWORK');
CL: CRTBNDCL PGM(ACS_5OBJ/TS_DALWORK) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE) TEXT('Testing AC_DALWORK');
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_DALWORK) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


--------------------------------------------------------------------------------
-- Integrated Testing Environment
--------------------------------------------------------------------------------

-- AR_INVLOG
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_INVLOG) TOMBR(AR_INVLOG);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_INVLOG) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);

-- AC_INVLOG
CL: CPYSRCF FROMFILE(ACS_5DEV/QCLLESRC) TOFILE(WEB_5TDV/QCLLESRC) FROMMBR(AC_INVLOG) TOMBR(AC_INVLOG);
CL: CRTBNDCL PGM(WEB_5TST/AC_INVLOG) SRCFILE(WEB_5TDV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);

CL: GRTOBJAUT OBJ(WEB_5TST/AR_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);
CL: GRTOBJAUT OBJ(WEB_5TST/AC_INVLOG) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_INVLOG  todo: remove
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(AR_NITTOT) TOMBR(AR_NITTOT);
CL: CRTSQLRPGI OBJ(WEB_5TST/AR_NITTOT) SRCFILE(WEB_5TDV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);



--------------------------------------------------------------------------------
-- Deployment
--------------------------------------------------------------------------------

-- AR_DAYPROR
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_DAYPROR) TOMBR(AR_DAYPROR);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_DAYPROR) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);

CL: GRTOBJAUT OBJ(WEB_5OBJ/AR_DAYPROR) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_DAYPROR todo: remove
CL: CPYSRCF FROMFILE(WEB_5TDV/QRPGLESRC) TOFILE(WEB_5DEV/QRPGLESRC) FROMMBR(AR_NITTOT) TOMBR(AR_NITTOT);
CL: CRTSQLRPGI OBJ(WEB_5OBJ/AR_NITTOT) SRCFILE(WEB_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R2M0);



--------------------------------------------------------------------------------
-- Hotfix to FTP site
--------------------------------------------------------------------------------

-- Clear save file
CL: CLRSAVF FILE(QGPL/r6objects);

-- Add objects to save file
CL: SAVOBJ OBJ(AR_DAYPROR AC_DAYPROR) LIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/r6objects);

-- todo: remove
CL: SAVOBJ OBJ(AR_NITTOT) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/r6objects);

-- Upload savefile to Smartfile FTP site
--  (on Conan Dev)
FTP RMTSYS(K3S.SMARTFILE.COM)
> cd /R6_Deployment/Customer_Access
  250 "/R6_Deployment/Customer_Access" is the current directory.
> bin
  200 Type set to: Binary.
        > put r6objects                                                        
229 Entering extended passive mode (|||21344|).                            
125 Data connection already open. Transfer starting.                       
226 Transfer complete.                                                     
2356992 bytes transferred in 0.721 seconds. Transfer rate 3270.406 KB/sec. 
;


GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON FT_5DTA.K_COMPANY TO PUBLIC WITH GRANT OPTION ;


insert into FT_5DTA.K_USERPRF (US_USER, US_COMP, US_LOCN, US_BUYR, US_BIRTH, US_LASTUPD, US_DATFMT, US_TIMFMT, US_TIMADJS, US_ALARM, US_DEALAL, US_DEALPI, US_DATESIX, US_EWINDOW, US_ORDVIEW, US_ORDMODE, US_PRDVIEW, US_PRDOPTN, US_HISDSPL, US_TRACKSG, US_UNITDSP, US_SELCHEK, US_PRODSUM, US_MULTWRN, US_ALTVIEW, US_LOGWARN, US_EXPNOTE, US_F3_WARN, US_CUR1010, US_CSTWARN, US_ARVDATE, US_AUTORND, US_AUTOFRZ, US_DFTLFRZ, US_SELVIEW)
values(
'CHUK', 
'C', 
'1    ', 'JLB  ', '2020-06-09', '2020-06-09', '*USA', '*USA', '0', '1', '$', '%', '0', '1', '2', 'D', '3', '1', '0', '0.300', '2', '' , '1', '1', '1', '60', '60', '0', '0', '0', '0', '0', '0', '', 
'1'
); 



