--------------------------------------------------------------------------------
-- In Development
--------------------------------------------------------------------------------
-- DEVTOOLS/SETENV ENV(DEV)



-------------------------------
--    Service Programs
-------------------------------
CL: CALL PGM(DEVTOOLS/APISRVPGM) PARM('AR_MFUBHED' 'ACS_5DEV' 'QRPGLESRC' 'ACS_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APISRVPGM) PARM('AR_MFUBENT' 'ACS_5DEV' 'QRPGLESRC' 'ACS_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APISRVPGM) PARM('AS_MFUBCH' 'ACS_5DEV' 'QRPGLESRC' 'ACS_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: Call PGM(DEVTOOLS/APISRVPGM) PARM('AR_INTMFUB' 'ACS_5DEV' 'QRPGLESRC' 'ACS_5OBJ' 'QSRVSRC' 'K3SDIR');

-------------------------------
--          APIs
-------------------------------
-- AR_ADDMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_ADDMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_ADDMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_ADDMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_ADDMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_ADDMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_ADDMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_ADDMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_ADDMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_DELMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_DELMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_DELMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_DELMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_DELMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_DELMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_DELMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_DELMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_DELMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_UPBMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_UPBMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_UPBMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_UPBMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_UPBMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_UPBMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_UPBMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_UPBMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_UPBMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_LCKMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_LCKMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_LCKMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_LCKMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_LCKMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_LCKMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_LCKMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_LCKMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_LCKMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_UNLMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_UNLMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_UNLMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_UNLMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_UNLMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_UNLMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_UNLMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_UNLMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_UNLMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_ADEMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_ADEMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_ADEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_ADEMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_ADEMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_ADEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_ADEMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_ADEMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_ADEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_DLEMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_DLEMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_DLEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_DLEMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_DLEMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_DLEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_DLEMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_DLEMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_DLEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);


-- AR_UPEMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_UPEMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_UPEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_UPEMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_UPEMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_UPEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_UPEMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_UPEMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_UPEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_GBEMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_GBEMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_GBEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_GBEMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_GBEMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_GBEMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);



-- AR_GENMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_GENMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_GENMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_GENMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_GENMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_GENMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_GENMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_GENMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_GENMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_PROMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_PROMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_PROMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_PROMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_PROMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_PROMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_PROMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_PROMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_PROMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AR_REVMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_REVMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_REVMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_REVMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_REVMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_REVMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_REVMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_REVMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_REVMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);




-- AR_IMPMFUB
CL: CRTSQLRPGI OBJ(ACS_5OBJ/AR_IMPMFUB) SRCFILE(ACS_5DEV/QRPGLESRC) COMMIT(*NONE) OPTION(*EVENTF *XREF) DBGVIEW(*SOURCE) TGTRLS(V7R3M0);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AR_IMPMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- AC_IMPMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/AC_IMPMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/AC_IMPMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);

-- TS_IMPMFUB
CL: CRTBNDCL PGM(ACS_5OBJ/TS_IMPMFUB) SRCFILE(ACS_5DEV/QCLLESRC) OPTION(*EVENTF) DBGVIEW(*SOURCE);
CL: GRTOBJAUT OBJ(ACS_5OBJ/TS_IMPMFUB) OBJTYPE(*PGM) USER(*PUBLIC) AUT(*ALL);



--------------------------------------------------------------------------------
-- Integrated Testing Environment
--------------------------------------------------------------------------------
-- DEVTOOLS/SETENV ENV(ITE)

-- Tables
CL: CPYSRCF FROMFILE(ACS_5DEV/QDDSSRC) TOFILE(WEB_5TDV/QDDSSRC) FROMMBR(K_MFUBHED) TOMBR(K_MFUBHED);
CL: DLTF FILE(WEB_5MOD/K_MFUBHED);
CL: CRTPF FILE(WEB_5MOD/K_MFUBHED) SRCFILE(ACS_5DEV/QDDSSRC) SRCMBR(K_MFUBHED) IGCDTA(*N);

CL: CPYSRCF FROMFILE(ACS_5DEV/QDDSSRC) TOFILE(WEB_5TDV/QDDSSRC) FROMMBR(K_MFUBENT) TOMBR(K_MFUBENT);
CL: DLTF FILE(WEB_5MOD/K_MFUBENT);
CL: CRTPF FILE(WEB_5MOD/K_MFUBENT) SRCFILE(ACS_5DEV/QDDSSRC) SRCMBR(K_MFUBENT) IGCDTA(*N);

CL: CPYSRCF FROMFILE(ACS_5DEV/QDDSSRC) TOFILE(WEB_5TDV/QDDSSRC) FROMMBR(K_INTMFUB) TOMBR(K_INTMFUB);
CL: DLTF FILE(WEB_5MOD/K_INTMFUB);
CL: CRTPF FILE(WEB_5MOD/K_INTMFUB) SRCFILE(ACS_5DEV/QDDSSRC) SRCMBR(K_INTMFUB) IGCDTA(*N);

CL: CPYSRCF FROMFILE(ACS_5WEB/QRPGLESRC) TOFILE(WEB_5WEB/QRPGLESRC) FROMMBR(K3S_APIPRO) TOMBR(K3S_APIPRO);

-- Prototype header source
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(MFUBHED_H) TOMBR(MFUBHED_H);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(MFUBENT_H) TOMBR(MFUBENT_H);
CL: CPYSRCF FROMFILE(ACS_5DEV/QRPGLESRC) TOFILE(WEB_5TDV/QRPGLESRC) FROMMBR(MFUBCH_H) TOMBR(MFUBCH_H);

-- Service programs
CL: CALL PGM(ACS_5OBJ/APIPRSRVT) PARM('AR_MFUBHED' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRSRVT) PARM('AR_MFUBENT' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRSRVT) PARM('AS_MFUBCH' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRSRVT) PARM('AR_INTMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRSRVT) PARM('AR_PRODUCT' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');

-- APIs
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_ADDMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_DELMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_UPBMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_LCKMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_UNLMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_ADEMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_DLEMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_UPEMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_PROMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_IMPMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_GBEMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRART) PARM('AR_USRMFUB' 'ACS_5DEV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');

-- CL Wrappers
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_ADDMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_DELMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_UPBMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_LCKMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_UNLMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_ADEMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_DLEMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_UPEMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_PROMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_IMPMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_GBEMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_USRMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');

-- Tests
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_ADDMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_DELMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_UPBMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_LCKMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_UNLMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_ADEMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_DLEMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_UPEMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_PROMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_IMPMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_GBEMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('TS_USRMFUB' 'ACS_5DEV' 'QCLLESRC' 'QCLLESRC' 'WEB_5TDV' 'WEB_5TST' 'QSRVSRC' 'K3SDIR');



--------------------------------------------------------------------------------
-- Deployment
--------------------------------------------------------------------------------
-- DEVTOOLS/SETENV ENV(DPL)

-- Service Programs
CL: CALL PGM(DEVTOOLS/APIPRSRVT) PARM('AR_MFUBHED' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRSRVT) PARM('AR_MFUBENT' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRSRVT) PARM('AS_MFUBCH' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRSRVT) PARM('AR_INTMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRSRVT) PARM('AR_PRODUCT' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');

-- APIs
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_ADDMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_DELMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_UPBMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_LCKMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_UNLMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_ADEMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_DLEMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_UPEMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_PROMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_IMPMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_GBEMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_USRMFUB' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');

CL: CALL PGM(DEVTOOLS/APIPRARD) PARM('AR_NOTPATH' 'WEB_5TDV' 'QRPGLESRC' 'QRPGLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_PSIREPT' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(DEVTOOLS/APIPRACT) PARM('AC_PTHREPT' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');


-- CL Wrappers
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_ADDMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_DELMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_UPBMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_LCKMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_UNLMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_ADEMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_DLEMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_UPEMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_PROMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_IMPMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_GBEMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('AC_USRMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');

-- Tests
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_ADDMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_DELMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_UPBMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_LCKMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_UNLMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_ADEMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_DLEMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_UPEMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_PROMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_IMPMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_GBEMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');
CL: CALL PGM(ACS_5OBJ/APIPRACT) PARM('TS_USRMFUB' 'WEB_5TDV' 'QCLLESRC' 'QCLLESRC' 'WEB_5DEV' 'WEB_5OBJ' 'QSRVSRC' 'K3SDIR');


-- Set to current date
CL: CHGDTAARA DTAARA(WEB_5OBJ/AR_RELEASE *ALL) VALUE('040622');

--------------------------------------------------------------------------------
-- Hotfix to FTP site
--------------------------------------------------------------------------------

-- Clear save file
CL: CLRSAVF FILE(QGPL/k3shotfix);

-- Add objects to save file
CL: SAVOBJ OBJ(AC_PSIMIS AR_INVRLOG AS_SSTOCK AS_PRDINVT AR_PRDINVT AC_PRDINVT AR_INVLOG AC_INVLOG AR_PSIREPT) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/k3shotfix);
CL: SAVOBJ OBJ(AR_ADJAPOR) LIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/k3shotfix);

-- Upload savefile to Smartfile FTP site
--  (on Conan Dev)
FTP RMTSYS(K3S.SMARTFILE.COM)
> cd /R6_Deployment/Customer_Access
  250 "/R6_Deployment/Customer_Access" is the current directory.
> bin
  200 Type set to: Binary.
        > put r6objects
229 Entering extended passive mode (|||21344|).                            
125 Data connection already open. Transfer starting.                       
226 Transfer complete.                                                     
2356992 bytes transferred in 0.721 seconds. Transfer rate 3270.406 KB/sec. 
;



-- Hotfix to Conan DR

-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API objects to save file
CL: SAVOBJ OBJ(AR_INVLOG) LIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Transfer save file
CL: CALL QGPL/CBEANPUTDR;

-- on Conan DR...
CL: RSTOBJ OBJ(AR_INVLOG) SAVLIB(ACS_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK) RSTLIB(RES_5OBJ) ALWOBJDIF(*ALL) MBROPT(*ALL);


select distinct(XE_PROD), (select XE from (select XE_PROD, XE_LOCN from cmm_5dev.dalyint2 group by XE_PROD, XE_LOCN);


--------------------------------------------------------------------------------
-- Hotfix to hosted
--------------------------------------------------------------------------------
-- Clear the save file
CL: CLRSAVF FILE(QGPL/APIMISSCHK);

-- Add API object in error to save file
CL: SAVOBJ OBJ(AR_MFUBHED AR_MFUBENT AS_MFUBCH AR_INTMFUB AR_PRODUCT AR_ADDMFUB AR_DELMFUB AR_UPBMFUB AR_LCKMFUB AR_UNLMFUB AR_ADEMFUB AR_DLEMFUB AR_UPEMFUB AR_PROMFUB AR_IMPMFUB AR_GBEMFUB AR_USRMFUB AC_ADDMFUB AC_DELMFUB AC_UPBMFUB AC_LCKMFUB AC_UNLMFUB AC_ADEMFUB AC_DLEMFUB AC_UPEMFUB AC_PROMFUB AC_IMPMFUB AC_GBEMFUB AC_USRMFUB TS_ADDMFUB TS_DELMFUB TS_UPBMFUB TS_LCKMFUB TS_UNLMFUB TS_ADEMFUB TS_DLEMFUB TS_UPEMFUB TS_PROMFUB TS_IMPMFUB TS_GBEMFUB TS_USRMFUB) LIB(WEB_5OBJ) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);

-- Add API object in error to save file
CL: SAVOBJ OBJ(K_MFUBHED K_MFUBENT K_INTMFUB) LIB(WEB_5MOD) DEV(*SAVF) SAVF(QGPL/APIMISSCHK);


CL: CRTPF FILE(WEB_5MOD/K_MFUBHED) SRCFILE(ACS_5DEV/QDDSSRC) SRCMBR(K_MFUBHED) IGCDTA(*N);
CL: CRTPF FILE(WEB_5MOD/K_MFUBENT) SRCFILE(ACS_5DEV/QDDSSRC) SRCMBR(K_MFUBENT) IGCDTA(*N);
CL: CRTPF FILE(WEB_5MOD/K_INTMFUB) SRCFILE(ACS_5DEV/QDDSSRC) SRCMBR(K_INTMFUB) IGCDTA(*N);










-- Transfer save file
CL: CALL QGPL/CBEAN_PUTL;

-- on Leno...

-- Restore the save file objects to library DMO
CL: RSTOBJ OBJ(*ALL) SAVLIB(ACS_5DEV) DEV(*SAVF) SAVF(QGPL/APIMISSCHK) RSTLIB(DMO_5OBJ) ALWOBJDIF(*ALL) MBROPT(*ALL);
